# Generated by Django 5.2.1 on 2025-06-02 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spotify_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('spotify_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(max_length=500)),
                ('expires_in', models.DateTimeField()),
                ('token_type', models.CharField(max_length=255)),
                ('jwt_token', models.TextField(blank=True, null=True)),
                ('jwt_expires_in', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
