# Generated by Django 5.2.1 on 2025-05-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberMGT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='jwt_expires_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='jwt_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
