# Generated by Django 5.2.1 on 2025-05-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberMGT', '0002_token_jwt_expires_in_token_jwt_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='user',
            new_name='spotify_id',
        ),
    ]
