# Generated by Django 5.2.1 on 2025-05-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberMGT', '0003_rename_user_token_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='spotify_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
